### ISSUE TITLE
How to get duration of a video?

### ISSUE THREAD

**Issue by kankadev** [caprica/vlcj-examples#1]
Hi,

is there an example how to get the duration of a video? I checked a lot of directories here but couldn't find anything. 
I want to get the duration and to show it in a column of a TableView (JavaFX).

Example:
| Filename | Duration |
| x.mp4 | 3h 20 min |
| a.mp4 | 30 min |

Thanks.

**Comment by caprica** [comment]
```
mediaPlayer().status().length();
```
