### ISSUE TITLE
Building Examples

### ISSUE THREAD

**Issue by jmccay-work** [caprica/vlcj-examples#2]
I am trying to build the examples using OpenJDK 8 ( (Zulu 8.68.0.21-CA-linux64) (build 1.8.0_362-b09) ), but I am getting an error.  An artifact can't be found.

```Could not find artifact uk.co.caprica:vlcj:jar:5.0.0-SNAPSHOT```

Is it possible to compile it use 3.12.1?

**Comment by caprica** [comment]
For 3.12.1, the examples you need are in the src/test directory in the vlcj project itself, not vlcj-examples.

**Comment by caprica** [comment]
https://github.com/caprica/vlcj/tree/vlcj-3.12.1/src/test/java/uk/co/caprica/vlcj/test

**Comment by jmccay-work** [comment]
Thank you.
