### ISSUE TITLE
Add example for m3u8 (vlc network stream)

### ISSUE THREAD

**Issue by slyk26** [caprica/vlcj-examples#3]
Most examples show how to setup a java swing application and start a file. 

However there are no examples for network streams with e.g. m3u8 streams and how to handle them.

for example:

* how to change from one .m3u8 to another (just using play does not work)
* finish listener would never finish because playlist never stops?

would be nice to have a example for that scenario added

**Comment by caprica** [comment]
Look for any example that uses a MediaListPlayer.

If you don't get a finish event, well, vlcj will deliver any event so long as LibVLC sends it.

**Comment by slyk26** [comment]
This was my mistake - my m3u8 files where not valid lol.

i double checked with this example (thanks for reminding me about the class) https://github.com/caprica/vlcj-examples/blob/6c0fc57f5ee982ee4c07a8cd758259f136b25758/src/main/java/uk/co/caprica/vlcj/test/list/TestMediaListPlayer.java

anyway, i was surprised about the fast response. have a good one
